mock_data/dummyData.ts
package-lock.json
package.json
src/app/guest/page.tsx
src/types/products.ts

moved react-datepicker and react-day-picker to devDependencies.
moved type Product in types/product
downgraded to react v18.3.1 and next v14.2.4

fix: fixed package-lock and package.json conflict (temporary).

---

src/app/guest/page.tsx
src/components/Header.tsx

(guest page) - searach returns empty if no match found
(header) - change extension of logo image src from svg to png

minor fix:

---

src/app/auth/page.tsx
src/contexts/AuthContext.tsx

added signup page
added signup to AuthContext

Login Page/Sign Up Page

---

package-lock.json
package.json
prisma/migrations/20241119083127_init/migration.sql
prisma/schema.prisma

Prisma-Supabase setup

---

src/app/guest/page.tsx
src/components/modals/MSMEModal.tsx

This pull request includes several updates to the `GuestPage` and `MSMEModal` components to improve their functionality and user experience. The most important changes include the removal of pagination, enhancements to the MSME sorting and filtering logic, and UI improvements to the MSME cards and modal.
* Removed pagination logic and related components, simplifying the display of MSMEs. [[1]](diffhunk://#diff-09f01a01c0112d683e305f59bc3635926b4d6626f88a00287aad6c5040d02d24L22-R28) [[2]](diffhunk://#diff-09f01a01c0112d683e305f59bc3635926b4d6626f88a00287aad6c5040d02d24L71-R108)
* Improved the MSME sorting function to create a new sorted array instead of mutating the original array.
* Enhanced the search and filter functionality to reset results and queries appropriately.
* Updated the UI …

Refactor: enhance UI of MSME guest page

---

src/app/guest/page.tsx
src/components/guest/Pagination.tsx
src/components/modals/MSMEModal.tsx

- Jezerwel
- Aaron
```
added pagination to guest page, added adjustment support on MSME modal for devices with smaller screens.
```
Note: pls pull first and check on your device if feature is working as intended.

feat: added pagination to guest page

---

src/app/api/auth/session/route.ts
src/lib/auth-handlers.ts
src/services/auth-service.ts
src/types/auth.ts

**-  Jezerwel Griño**
This pull request includes several changes to improve error handling and validation in the authentication and user management system. The most important changes include refining the error handling in the `GET` function, updating the `handleLogin` and `handleLogout` functions, enhancing the user validation logic, and updating the `CustomAuthError` type.
Improvements to error handling:
* [`src/app/api/auth/session/route.ts`](diffhunk://#diff-0f090cc1311ae8f156b284ade8dcdbd8afdb54a202549863441f0b6faa88a0e7L5-R20): Refined error handling in the `GET` function to differentiate between missing authentication sessions and unexpected errors. [[1]](diffhunk://#diff-0f090cc1311ae8f156b284ade8dcdbd8afdb54a202549863441f0b6faa88a0e7L5-R20) …

refactor(auth): improve error handling and enhance auth handlers

---

src/lib/auth-handlers.ts

fix(auth): fix auth-handler bugs

---

package-lock.json
package.json
src/app/admin/msme/page.tsx
src/app/layout.tsx
src/app/login/page.tsx
src/app/signup/page.tsx
src/components/AdminSidebar.tsx
src/components/sidebar/Sidebar.tsx
src/contexts/AuthContext.tsx
src/contexts/SuperAdminContext.tsx

This pull request focuses on improving the user feedback by enhancing the toast notifications across various components and pages. The changes ensure that success and error messages are more clearly distinguished and provide better user experience.
* [`src/app/admin/msme/page.tsx`](diffhunk://#diff-dfd626b23c32edbca68e4916aad892a18d5dd7599de289c7c418cfad5c29bb4eL150-R150): Changed the success message for MSME deletion to use `toast.success` for clearer feedback.
* [`src/app/layout.tsx`](diffhunk://#diff-29d0a55f5ca1a9951042587f8b891bb4cd8b204f5bc855dc2468ed44cde2f5b3L14-R14): Updated the `Toaster` component to use rich colors, position it at the bottom-right, and include a close button for better user interaction.
* [`src/app/login/page.tsx`](diffhunk://#diff-31585754d24e6f4fc13389cbce00c5 …

chore: update toast notifications with colors and symbols

---

src/app/admin/dashboard/[sectorName]/page.tsx
src/app/admin/export-data/[sectorName]/page.tsx
src/app/admin/layout.tsx
src/app/admin/msme/[sectorName]/page.tsx
src/app/admin/msme/page.tsx
src/app/api/admin/[id]/sector/route.ts
src/components/AdminNavbar.tsx
src/components/AdminSidebar.tsx
src/components/admin/DashboardCardView.tsx
src/components/admin/cardView.tsx
src/components/admin/exportCardView.tsx
src/components/modals/AdminAddMSMEModal.tsx
src/components/modals/AdminEditMSMEModal.tsx
src/contexts/AuthContext.tsx

- [Manaf]
This PR implements several key improvements to the admin dashboard functionality:
1. Fixed infinite API calls issue in AdminSidebar
2. Added dynamic sector-based routing
3. Implemented admin name display in navbar
4. Fixed MSME modal sector selection
- None identified
- AdminAddMSMEModal now requires user's sector information
- Sidebar navigation now requires sector information for routing
- Added cleanup function to prevent memory leaks in AdminSidebar
- Improved error handling for sector fetching
- Added proper type checking for API responses
Before submitting the PR, please check that you have:
| Before | After |
|--------|-------|
| [Image] | [Image] |
Steps to test these changes: …

feat: Admin UI Update

---

src/app/admin/dashboard/[sectorName]/page.tsx
src/app/admin/export-data/[sectorName]/page.tsx
src/app/admin/msme/[sectorName]/page.tsx
src/components/admin/municipalityChart.tsx
src/components/admin/sectorPieChart.tsx
src/components/admin/totalSectorMSMEChart.tsx

- [Manaf]
-  Added TopMunicipalitiesChart component for geographic distribution
-  Added SectorPieChart for sector-wise MSME distribution
- Added TotalSectorMSMEChart for numeric visualization
-  Implemented responsive 3-column layout
- Enhanced search and filter functionality
- Company name
- Municipalit
when adding or updating MSME their a short time fetching sector
L

feat:  Added Admin Charts 

---

src/app/admin/dashboard/page.tsx
src/app/admin/msme/page.tsx
src/app/api/admin/pending/route.ts
src/app/api/msme/[id]/route.ts
src/app/api/msme/route.ts
src/app/superadmin/msme/page.tsx
src/app/superadmin/pdf-export/page.tsx
src/components/dashboard/ExportsLineChart.tsx
src/components/modals/AddMSMEModal.tsx
src/components/modals/AdminAddMSMEModal.tsx
src/components/modals/EditMSMEModal.tsx
src/components/modals/ImageCropModal.tsx
src/components/modals/MSMEModal.tsx
src/components/sidebar/Sidebar.tsx
src/components/ui/command.tsx
src/components/ui/dropdown-menu.tsx
src/lib/msme-utils.ts
src/types/MSME.ts
src/utils/imageUtils.ts
src/utils/supabase/storage.ts

- [Manaf]
fix export pdf route lint error
```
[Brief description here]
```
List any breaking changes and required actions:
```
- Change 1: [Required Action]
- Change 2: [Required Action]
```

fix: fix lint error on pdf route

---

src/app/admin/csv-export/page.tsx
src/app/admin/export-data/page.tsx
src/app/admin/msme/[sectorName]/page.tsx
src/app/admin/msme/page.tsx
src/components/AdminSidebar.tsx
src/components/admin/MSMETable.tsx

- [Aaron]
- [Manaf]
fix lint errors
added export to csv
- export to csv

Fix: Lint Errors UI

---

.eslintrc.cjs
lint-staged.config.cjs
next.config.js
src/app/export/page.tsx
src/app/guest/layout.tsx
src/app/guest/page.tsx
src/app/msme/[id]/page.tsx
src/components/Footer.tsx
src/components/Header.tsx
src/components/modals/EditMSMEModal.tsx

- [Aaron]
- [Jez]
```
[Fixed some linting errors according to eslint]
```

chore: fix lint errors/warnings

---

src/app/api/msme/route.ts
src/components/modals/AdminAddMSMEModal.tsx
src/components/modals/EditMSMEModal.tsx

- [Manaf]
added pin location on edit msme

feat:added pinlocation superadmin edit msme

---

src/app/api/msme/paginated-msme/[page]/route.ts
src/app/api/msme/sector-filter/[sectorName]/[page]/route.ts
src/app/msme/[id]/page.tsx
src/components/guest/FilterSection.tsx
src/components/guest/GuestPageContent.tsx
src/components/guest/GuestPagePagination.tsx
src/components/guest/MSMEList.tsx
src/contexts/MSMEContext.tsx

- [Aaron]
```
[Refactor GuestPage, MSMEPage, and MSMEList components for improved readability and performance]
```

fix: Refactor GuestPage, MSMEPage, and MSMEList

---

src/components/guest/GuestPageContent.tsx
src/components/guest/MSMEList.tsx

- Manaf
```
[Brief description here]
```
- minor ui  changes

Fix: Guest Page UI

---

src/app/api/msme/paginated-msme/[page]/route.ts
src/app/api/msme/sector-filter/[sectorName]/[page]/route.ts
src/components/guest/GuestPageContent.tsx
src/contexts/MSMEContext.tsx

- [Aaron]
```
[Modified guest page filter to fetch from backend]
```

feat: Guest page filter

---

src/app/layout.tsx

fix: issue where landing-page and guest page are unscrollable

fix: issue where landing-page and guest page are unscrollable

---

src/app/admin/layout.tsx
src/app/admin/msme/addmsme/[sectorName]/page.tsx
src/app/admin/msme/edit/[id]/page.tsx

fix: fix logo upload functionality and update navigation for MSME pages

---

src/app/api/admin/approve/route.ts

- Faith
```
Updated the email template for admin approval
```
- New email template to be sent upon admin approval
- None
- None
- None
List any known issues or limitations:
```
- None
```
List any breaking changes and required actions:
```
- None
```

fix: enhanced email template

---

src/app/admin/msme/edit/[id]/page.tsx

Manaf
```
[Brief description here]
refactor admin edit page

Fix Admin Edit Msme

---

src/components/guest-export/index.tsx
src/lib/municipalities.ts

- Faith
```
Corrected municipality names
```
- None
- None
- None
- None
List any known issues or limitations:
```
- None
```
List any breaking changes and required actions:
```
None
```

fix: corrected municipality names

---

src/app/msme/[id]/page.tsx
src/components/guest/MSMEList.tsx

refactor: implement sector colors on badges and reorganized msme details

---

prisma/schema.prisma
src/app/admin/csv-export/page.tsx
src/app/admin/dashboard/[sectorName]/page.tsx
src/app/admin/layout.tsx
src/app/superadmin/layout.tsx
src/app/superadmin/msme/page.tsx
src/components/admin/municipalityChart.tsx
src/components/guest-export/index.tsx
src/components/guest/GuestPageContent.tsx

- [Aaron]
```
[made visitor and export contents cascade on delete]
[removed overflow on admin and superadmin MSME and add-msme page]
[added record export csv on admin, superadmin, and guest page]
[reset search query upon reset filter on guest page]
```

fix: random bug fixes

---

src/app/admin/msme/addmsme/[sectorName]/page.tsx
src/app/admin/msme/edit/[id]/page.tsx
src/app/superadmin/msme/add-msme/page.tsx
src/app/superadmin/msme/edit-msme/[id]/page.tsx

- [Aaron]
```
[Added map location autocomplete on admin and superadmin msme forms]
```

feat: google maps location autocomplete

---

src/app/superadmin/msme/page.tsx
src/components/dashboard/SectorPieChart.tsx
src/components/msme/MSMETable.tsx

fix: responsiveness
